apiVersion: v1
kind: ReplicationController
metadata:
  name: erep-1
spec:
  replicas: 1  
  selector:    
    name: erep-1
  template:    
    metadata:
      labels:  
        name: erep1 
    spec:
      containers:
      - image: pthopa/elastic:v1.0.0
        name: elastictest
        ports:
        - containerPort: 9200
          name: "http"
        - containerPort: 9300
          name: "transport"
      restartPolicy: Always
