apiVersion: v1
kind: ReplicationController
metadata:
  name: erep-3master
spec:
  replicas: 1  
  selector:    
    name: erep-3master
  template:    
    metadata:
      labels:  
        name: erep-3master
    spec:
      containers:
      - image: pthopa/elastic:v1.0.0
        name: elastictest
        ports:
        - containerPort: 9300
          name: "transport"
    restartPolicy: Always
