apiVersion: v1
kind: Service
metadata:
  name: elasticsearchcluster
  namespace: elasticsearch
spec:
  selector:
    component: "elasticsearch"
    provider: "fabric8"
  clusterIP: "None"
  ports:
    - protocol: TCP
      port: 9300
      targetPort: 9300